api/urls.py
from django.urls import path
from rest_framework_swagger.views import get_swagger_view

from . import views as api_views

app_name = 'api'


schema_view = get_swagger_view(title='Tyne Music Api')


urlpatterns = [
    # docs/
    path('', schema_view, name='docs'),

    # /home-data/
    path('home-data/', api_views.HomeData.as_view(), name='home-data'),

    # categories/
    path('categories/', api_views.FetchCategories.as_view(), name='fetch-categories'),

    # albums/
    path('albums/', api_views.FetchAlbums.as_view(), name='fetch-albums'),

    # albums/invasion-of-privacy/
    path('albums/<slug:album_slug>/', api_views.FetchAlbum.as_view(), name='get-album'),

    # albums/invasion-of-privacy/songs/
    path('albums/<slug:album_slug>/songs/', api_views.FetchAlbumSongs.as_view(), name='fetch-album-songs'),

    # artists/
    path('artists/', api_views.FetchArtists.as_view(), name='fetch-artists'),

    # artists/ed-sheraan/
    path('artists/<slug:artist_slug>/', api_views.FetchArtist.as_view(), name='get-artist'),

    # genres/
    path('genres/', api_views.FetchGenres.as_view(), name='fetch-genres'),

    # genres/rb/
    path('genres/<slug:genre_slug>/', api_views.FetchGenre.as_view(), name='get-genre'),

]

music/urls.py
from django.urls import path

from . import views


app_name = "music"


urlpatterns = [

    # music/
    path('', views.MusicIndex.as_view(), name="index"),

    # music/album/divide/
    path('album/<slug:slug>/', views.AlbumPage.as_view(), name="album"),

    # /music/artist/ed-sheraan-1/
    path('artist/<slug:slug>/', views.ArtistPage.as_view(), name="artist"),

    # /music/genre/r&b/
    path('genre/<genre_name>/', views.GenrePage.as_view(), name="genre"),

]

tyne/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # /admin/
    path('admin/', admin.site.urls),

    # /music/
    path('music/', include('music.urls')),

    # /api/
    path('api/', include('api.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tyne/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#343a40">
        <title>tyne music | {% block title %}home{% endblock title %}</title>
        <link rel='stylesheet' type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel='stylesheet' type="text/css" href="{% static 'css/base.css' %}">
        {% block style %}{% endblock style %}
    </head>
    <body>
        <nav id="navbar" class="navbar navbar-expand-lg navbar-dark bg-dark">
            <h1>tyne music</h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link {% block home %}{% endblock home %}" href="{% url 'music:index' %}">home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% block accounts %}{% endblock accounts %}" href="">accounts</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% block settings %}{% endblock settings %}" href="">settings</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% block help %}{% endblock help %}" href="">help</a>
                </li>

            </ul>

            <form id="top-search-bar" method="GET" action="" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-4" type="search" name="query" value="" placeholder="Search for music" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

          </div>
      </nav>
      
      <div id="content-main">
      {% block content %}
      
      {% endblock content %}
      </div>

        <footer class="section footer-classic context-dark bg-image" style="background: #2d3246;">
            <div class="container">
                <div class="row row-30">
                    <div class="col-md-4 col-xl-5">
                        <div class="pr-xl-4"><a class="brand" href="{% url 'music:index' %}"><!--<img class="brand-logo-light" src="images/agency/logo-inverse-140x37.png" alt="" width="140" height="37" srcset="images/agency/logo-retina-inverse-280x74.png 2x">--><h1>tyne music</h1></a>
                            <p>We are an award-winning music streaming site, dedicated to the best service, quality, and customer service.</p>
                            <!-- Rights-->
                            <p class="rights"><span>©  2019 - </span><span class="copyright-year" id="copy-year"></span><span> </span>. <span>HOUSE OF M</span><span>. </span><span>All Rights Reserved.</span></p>
                            <script type="text/javascript">
                                var date = new Date();
                                document.getElementById("copy-year").innerText = date.getFullYear();
                            </script>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <h5>Contacts</h5>
                        <dl class="contact-list">
                            <dt>Address:</dt>
                            <dd>P.O. Box 2000 Kiambu</dd>
                        </dl>
                        <dl class="contact-list">
                            <dt>email:</dt>
                            <dd><a href="mailto:#">customerservice@tyne.com</a></dd>
                        </dl>
                        <dl class="contact-list">
                            <dt>phones:</dt>
                            <dd><a href="tel:#">+254 5685430129</a> <span>or</span> <a href="tel:#">+254 9571195353</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="col-md-4 col-xl-3">
                        <h5>Links</h5>
                        <ul class="nav-list">
                            <li><a href="#">accounts</a></li>
                            <li><a href="#">help</a></li>
                            <li><a href="#">contacts</a></li>
                            <li><a href="#">pricing</a></li>
                            <li><a href="#">house of M</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>

        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/base.js' %}"></script>
        {% block script %}{% endblock script %}

    </body>
</html>